<?php
/**
 * Extended mass action block for Akeneo grid
 *
 * @var \Magento\Backend\Block\Widget\Grid\Massaction\Extended $block
 * @var \Magento\Framework\Escaper $escaper
 */

$escaper = $block->getEscaper();
?>
<div id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>">
    <div class="massaction">
        <div class="entry-edit">
            <?php if ($block->getHideFormElement() !== true): ?>
                <form action="" id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-form" method="post">
            <?php endif; ?>
                    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
                    <span class="field-row">
                        <label class="label"><?= $escaper->escapeHtml(__('Select Product Actions')) ?></label>
                        <select id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-select"
                                class="select absolute-advice local-validation">
                            <option value=""><?= $escaper->escapeHtml(__('-- Please select --')) ?></option>
                            <?php foreach ($block->getItems() as $_item): ?>
                                <option value="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"<?= $_item->getSelected() ? ' selected="selected"' : '' ?>>
                                    <?= $escaper->escapeHtml($_item->getLabel()) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </span>
                    <span class="outer-span" id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-form-hiddens"></span>
                    <span class="outer-span" id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-form-additional"></span>
                    <span class="field-row">
                        <?= /* @noEscape */ $block->getApplyButtonHtml() ?>
                    </span>
            <?php if ($block->getHideFormElement() !== true): ?>
                </form>
            <?php endif; ?>
            <div class="no-display">
                <?php foreach ($block->getItems() as $_item): ?>
                    <div id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-item-<?= $escaper->escapeHtmlAttr($_item->getId()) ?>-block">
                        <?= /* @noEscape */ $_item->getAdditionalActionBlockHtml() ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="entry-select">
            <select id="massaction-select" class="select">
                <option value="">
                    <?= $escaper->escapeHtml(__('Mass Actions')) ?>
                </option>
                <?php if ($block->getUseSelectAll()): ?>
                    <option value="selectAll">
                        <?= $escaper->escapeHtml(__('Select All')) ?>
                    </option>
                    <option value="unselectAll">
                        <?= $escaper->escapeHtml(__('Unselect All')) ?>
                    </option>
                <?php endif; ?>
                <option value="selectVisible">
                    <?= $escaper->escapeHtml(__('Select Visible')) ?>
                </option>
                <option value="unselectVisible">
                    <?= $escaper->escapeHtml(__('Unselect Visible')) ?>
                </option>
            </select>
            <span class="items">
                <strong id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>-count">0</strong>
                <?= $escaper->escapeHtml(__('items selected')) ?>
            </span>
        </div>
    </div>
    <script>
        require(['jquery'], function ($) {
            'use strict';

            $('#massaction-select').change(function () {
                var massAction = $('option:selected', this).val();

                switch (massAction) {
                    <?php if ($block->getUseSelectAll()): ?>
                    case 'selectAll':
                        return <?= /* @noEscape */ $block->getJsObjectName() ?>.selectAll();
                    case 'unselectAll':
                        return <?= /* @noEscape */ $block->getJsObjectName() ?>.unselectAll();
                    <?php endif; ?>
                    case 'selectVisible':
                        return <?= /* @noEscape */ $block->getJsObjectName() ?>.selectVisible();
                    case 'unselectVisible':
                        return <?= /* @noEscape */ $block->getJsObjectName() ?>.unselectVisible();
                }
            });
        });

        <?php if (!$block->getParentBlock()->canDisplayContainer()): ?>
            <?= /* @noEscape */ $block->getJsObjectName() ?>.setGridIds('<?= $escaper->escapeJs($block->getGridIdsJson()) ?>');
        <?php endif; ?>
    </script>
</div>
